### PR TITLE
Improved boombox

### PR DESCRIPTION
**Pull request by mugg91**
## Status

**READY**
- Tested offline and online without problems

## Description

This PR does the following changes:
* ArabicSpeaker and RussianSpeaker replaced by Boombox
* Boombox can have its radio channel switched by using a button
* I left support for the arabic and russian version in `BasePNGLoader.as`, so if a russianspeaker color is detected, it will create a boombox with the russian music.
* Boombox can drown when touching water
* Added a third music, "FanfareGerman", which is just a part of [Heinrich Steinbeck's Regimentsgruß](https://www.youtube.com/watch?v=5aDIxaCnDPQ). It is relatively neutral and since it was composed over 70 years ago, should be copyright free.
But feel free to remove or change it to your liking.

Fixes https://github.com/NoahTheLegend/kaww/issues/118

### CODE REVIEW

**Comment by mugg91** [comment]
Actually I messed up about copyright. The 70 years is after the person died, so it will take another 16 years or so before it becomes copyright free. If that is of any concern maybe we should not use that theme then.

**Comment by NoahTheLegend** [comment]
very good job, i did not find any code that syncs music for a player rejoined (though that doesnt matter much and will be added someday later)

**Comment by NoahTheLegend** [comment]
> Actually I messed up about copyright. The 70 years is after the person died, so it will take another 16 years or so before it becomes copyright free. If that is of any concern maybe we should not use that theme then.

that doesnt matter for real, the game isnt commercial and is very tiny in community

**Comment by mugg91** [comment]
I did testing only in base kag just adding the blob over. Because I couldn't figure out how to load the whole mod for testing, for now.

Anyway, I joined the server and the german theme was running, but the button for switching the channel didn't show up. Not sure why but we should look into fixing it.

**Pull request merged**
